const express = require('express')
const userController = require('../controllers/userController')
const routes = express();

routes.get("/", userController.getIndex)
routes.post("/login", userController.getLogin)
routes.get("/home", userController.getHome)
routes.get("/orders", userController.getOrders)
routes.get("/rfid", userController.getRFID)
routes.get("/notifications", userController.getNotifications)
routes.get("/registration", userController.getRegistration)
routes.post("/register", userController.postRegister)
routes.get("/users", userController.getUsers)
routes.get("/list_maintenance", userController.getListMaintenance)
routes.post("/addPlateNum", userController.postAddPlateNumber)
routes.post("/deletePlateNum", userController.postDeletePlateNumber)
routes.post("/addShippedVia", userController.postAddShippedVia)
routes.post("/deleteShippedVia", userController.postDeleteShippedVia)
routes.post("/addBusinessStyle", userController.postAddBusinessStyle)
routes.post("/deleteBusinessStyle", userController.postDeleteBusinessStyle)
routes.get("/profile", userController.getProfile)
routes.get("/order_details/:orderID", userController.getOrderDetails)
routes.get("/create_order", userController.getCreateOrder)
routes.post("/add-order", userController.postCreateOrder)
routes.post("/approve-order", userController.postApprovalOrder)
routes.post("/complete-order", userController.postCompleteOrder)
routes.post("/pending-order", userController.postPendingOrder)
routes.post("/resolve-order", userController.postResolveOrder)
routes.post("/updateUser", userController.postUpdateUser)
routes.post("/updateProfile", userController.postUpdateProfile)
routes.post("/deleteUser", userController.postDeleteUser)
routes.get("/signout", userController.getSignout)
routes.get("/average_branch", userController.getAllAverageBranch)
routes.get("/pending_orders", userController.getPendingOrders)
routes.get("/generate-order/:orderID", userController.getGenerateOrder)

module.exports = routes